package com.erecyclingcorps.dao.domain;

// Generated 29 Dec, 2014 5:11:33 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RefEmail generated by hbm2java
 */
@Entity
@Table(name = "ref_email", schema = "public")
@SequenceGenerator(initialValue = 1, name = "seq_pk", sequenceName = "ref_email_id_seq",allocationSize=1)
@NamedQueries({
    @NamedQuery(name = "getRetryEmails", query =  "select e.id as id, e.senderAddress as senderAddress, e.recipientAddress as recipientAddress,"
            + "e.subject as subject, e.message as message, e.program.programName as program "
            + "from Email e where e.program.id = :program and status='RETRY' and e.version<= :retrycount "),
    @NamedQuery(name = "getEmailbyId", query =  "from Email where id=:id")
})

public class Email implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1960094604916852783L;

    @Id
    @GeneratedValue(strategy =  GenerationType.SEQUENCE, generator = "seq_pk")
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "subject")
    private String subject;

    @Column(name = "message", nullable = false, length = 5000)
    private String message;

    @Column(name = "sender_address", nullable = false, length = 100)
    private String senderAddress;

    @Column(name = "recipient_address", nullable = false, length = 100)
    private String recipientAddress;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "sentdate", nullable = false, length = 35)
    private Date sentdate;

    @Column(name = "status", nullable = false, length = 100)
    private String status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "programid", nullable = false)
    private Program program;

    @Version
    @Column(name = "retry_count", nullable = true)
    private Long version=1L;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "retrydate", nullable = true, length = 35)
    private Date retrydate;

    public Email() {
    }

    public Email(Long id, String message, String senderAddress, String recipientAddress, Date sentdate,
            String status, Program program) {
        this.id = id;
        this.message = message;
        this.senderAddress = senderAddress;
        this.recipientAddress = recipientAddress;
        this.sentdate = sentdate;
        this.status = status;
        this.program = program;
    }

    public Email(Long id, String subject, String message, String senderAddress, String recipientAddress,
            Date sentdate, String status, Program program) {
        this.id = id;
        this.subject = subject;
        this.message = message;
        this.senderAddress = senderAddress;
        this.recipientAddress = recipientAddress;
        this.sentdate = sentdate;
        this.status = status;
        this.program = program;
    }
    public Email(String subject, String message, String senderAddress, String recipientAddress,
            Date sentdate, String status, Program program) {
        this.subject = subject;
        this.message = message;
        this.senderAddress = senderAddress;
        this.recipientAddress = recipientAddress;
        this.sentdate = sentdate;
        this.status = status;
        this.program = program;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getSenderAddress() {
        return this.senderAddress;
    }

    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    public String getRecipientAddress() {
        return this.recipientAddress;
    }

    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress;
    }

    public Date getSentdate() {
        return this.sentdate;
    }

    public void setSentdate(Date sentdate) {
        this.sentdate = sentdate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Program getProgram() {
        return this.program;
    }

    public void setProgram(Program program) {
        this.program = program;
    }

    public Long getRetryCount() {
        return version;
    }

    public void setRetryCount(Long retryCount) {
        this.version = retryCount;
    }

    public Date getRetrydate() {
        return retrydate;
    }

    public void setRetrydate(Date retrydate) {
        this.retrydate = retrydate;
    }

}
