package com.erecyclingcorps.dao.domain;

// Generated 24 Nov, 2014 10:40:04 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * RefManufacturer generated by hbm2java
 */
@Entity
@Table(name = "ref_manufacturer", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = "skucode"),
		@UniqueConstraint(columnNames = "description") })
public class Manufacturer implements java.io.Serializable {

	@Id
	@Column(name = "manufacturerid", unique = true, nullable = false)
	private long manufacturerId;
	
	@Version
	@Column(name = "version", nullable = false)
	private int version;
	
	@Column(name = "code")
	private String code;
	
	@Column(name = "description", unique = true, nullable = false)
	private String description;
	
	@Column(name = "skucode", unique = true, nullable = false)
	private String skucode;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate")
	private Date createdDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate")
	private Date lastUpdatedDate;
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="createdby")
	private User createdBy;
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="updatedby")
	private User updatedBy;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manufacturer")
	private Set<ManufacturerModel> models = new HashSet<ManufacturerModel>();

	public long getManufacturerId() {
		return manufacturerId;
	}

	public void setManufacturerId(long manufacturerId) {
		this.manufacturerId = manufacturerId;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSkucode() {
		return skucode;
	}

	public void setSkucode(String skucode) {
		this.skucode = skucode;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public User getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	public User getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set<ManufacturerModel> getModels() {
		return models;
	}

	public void setModels(Set<ManufacturerModel> models) {
		this.models = models;
	}


}
