package com.erecyclingcorps.dao.domain;

//Generated 24 Nov, 2014 10:40:04 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefProgramModelAttribute generated by hbm2java
 */
@Entity
@Table(name = "ref_program_model_attribute", schema = "public")
public class ProgramModelAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "programattributeid", unique = true, nullable = false)
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attributeid", nullable = false)
	private Attribute attribute;
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "description", nullable = false)
	@Column(name="description")
	private String label;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "programmodelcatgid", nullable = false)
	private ProgramManufacturerModel programManufacturerModel;

	@Column(name = "value", nullable = false)
	private String value;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Attribute getAttribute() {
		return attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public ProgramManufacturerModel getProgramManufacturerModel() {
		return programManufacturerModel;
	}

	public void setProgramManufacturerModel(ProgramManufacturerModel programManufacturerModel) {
		this.programManufacturerModel = programManufacturerModel;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}