package com.erecyclingcorps.dao.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefSearchAttributes generated by hbm2java
 */
@Entity
@Table(name = "ref_search_attributes")
public class SearchAttributes implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "searchattributeid", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attributeid", nullable = false)
	private Attribute attribute;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "programcategoryid", nullable = false)
	private ProgramCategory programCategory;

	@Column(name = "display_order", nullable = false)
	private long displayOrder;

	@Column(name = "code", nullable = false, length = 1000)
	private String code;

	@Column(name = "isactive", nullable = false)
	private boolean isactive;
	
	@Column(name = "label", nullable = false)
	private String label;
	
	@Column(name = "help_text", nullable = true)
	private String helpText;

	@Column(name="tigger", nullable = true)
	private String tigger;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Attribute getAttribute() {
		return attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	public ProgramCategory getProgramCategory() {
		return programCategory;
	}

	public void setProgramCategory(ProgramCategory programCategory) {
		this.programCategory = programCategory;
	}


	public long getDisplayOrder() {
		return displayOrder;
	}

	public void setDisplayOrder(long displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	public boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	/**
	 * @return the label
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * @param label the label to set
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * @return the helpText
	 */
	public String getHelpText() {
		return helpText;
	}

	/**
	 * @param helpText the helpText to set
	 */
	public void setHelpText(String helpText) {
		this.helpText = helpText;
	}

    public String getTigger() {
        return tigger;
    }

    public void setTigger(String tigger) {
        this.tigger = tigger;
    }
}
